version: "3.8"

services:
  posdb:
    image: mysql:8.0
    container_name: userdb
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    networks:
      - ng

  pos-system:
    image: soengkanel/pos-system:latest
    depends_on:
      posdb:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DB_HOST: posdb         # service name of the mysql container
      DB_PORT: 3306
      DB_NAME: userdb
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - ng

networks:
  ng:
